# Generated by Django 4.2.6 on 2023-10-23 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_delete_workemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
