# Generated by Django 4.2.6 on 2023-10-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_unit_full_name_alter_unit_short_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='place',
            new_name='location',
        ),
    ]
