# Generated by Django 4.2.6 on 2023-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_alter_expensedocumentlog_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedocumentlog',
            name='status',
            field=models.CharField(choices=[('ACC', 'Berkas Diterima'), ('NC', 'Berkas Tidak Lengkap'), ('CALC', 'Berkas Lengkap, Proses Penghitungan'), ('CMPLT', 'Penghitungan Selesai, Berkas Diserahkan ke Bendahara'), ('VRFY', 'Proses Verifikasi'), ('READY', 'Siap Dibayarkan'), ('DONE', 'Selesai Dibayarkan')], max_length=5),
        ),
    ]
