# Generated by Django 4.2.6 on 2023-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0008_alter_expensedocumentlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedocumentlog',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Berkas Diterima'), ('NOT_COMPLETE', 'Berkas Tidak Lengkap'), ('IN_CALCULATION', 'Berkas Lengkap, Proses Penghitungan'), ('CALCULATION_COMPLETED', 'Penghitungan Selesai, Berkas Diserahkan ke Bendahara'), ('FINAL_VERIFICATION', 'Proses Verifikasi'), ('READY_FOR_PAYMENT', 'Siap Dibayarkan'), ('DONE', 'Selesai Dibayarkan')], max_length=30),
        ),
    ]
