# Generated by Django 4.2.6 on 2023-11-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0009_alter_expensedocumentlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jenis Pengeluaran')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('expense_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensedocument')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensetype')),
            ],
        ),
    ]
