# Generated by Django 4.2.6 on 2023-11-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0011_alter_expensedocumentlog_expense_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Biaya Perjalanan Dinas', 'verbose_name_plural': 'Biaya Perjalanan Dinas'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'Jenis Biaya Perjalanan Dinas', 'verbose_name_plural': 'Jenis Biaya Perjalanan Dinas'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Nilai'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensetype', verbose_name='Jenis Biaya Perjalanan Dinas'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jenis Biaya Perjalanan Dinas'),
        ),
    ]
